### ISSUE TITLE
動作の本質が同じ関数はまとめた方が良い

### ISSUE THREAD

**Issue by hutinoatari** [kyu099/billgacha#1]
ここの関数達はやってることが同じで違うのは札の数だけなのでまとめた方が良い。例えば`displaySheets(sheetNum)`とか。
https://github.com/kyu099/billgacha/blob/0322d2bab768c17fecc4830dfce57eb2b757d432/main.js#L28-L57
この考え方はDRY原則(Don't Repeat Yourself)といって同じ動作をする関数をわざわざ2つ以上用意しないとかそんなニュアンス。どんな利点があるかというと仕様変更があった時に修正忘れを防げる、今の状態だと1つの仕様変更に対して3か所の変更が必要になってる。それが1か所の変更で済むようになるのでミスが減らせる。コードの見通しも良くなる(あと美しい)。要するに保守性が上がる。
関数はなるたけ再利用可能にするのがスマート。

(ちなみにonclickに引数ありの関数をセットする場合は無名関数にする必要がある)
```
elm.onclick = (function(){foo(bar)})();
elm.onclick = ()=>foo(bar);
```

**Comment by kyu099** [comment]
多分修正できた
またなんかあったら教えてください
今日はもう寝ます（14時）
